import { GlitchParams, Preset } from '@/types'

export const GLITCH_PRESETS: Preset<GlitchParams>[] = [
  {
    id: 'light-glitch',
    name: 'Light Glitch',
    nameZh: '轻微故障',
    params: {
      stripeDensity: 10,
      displacement: 15,
      verticalSpeed: 0,
      rgbSplit: 5,
      rgbSplitDirection: 0,
      rgbSplitDirectionAnim: false,
      clipShape: 'none',
      duotone: false,
      duotoneLightColor: '#e7305e',
      duotoneDarkColor: '#2e3060',
      dotSize: 2.2,
      dotOpacity: 0.28,
    },
  },
  {
    id: 'heavy-damage',
    name: 'Heavy Damage',
    nameZh: '重度损坏',
    params: {
      stripeDensity: 30,
      displacement: 20,
      verticalSpeed: 0,
      rgbSplit: 25,
      rgbSplitDirection: 0,
      rgbSplitDirectionAnim: false,
      clipShape: 'none',
      duotone: false,
      duotoneLightColor: '#e7305e',
      duotoneDarkColor: '#2e3060',
      dotSize: 2.2,
      dotOpacity: 0.28,
    },
  },
  {
    id: 'retro-crt',
    name: 'Retro CRT',
    nameZh: '复古 CRT',
    params: {
      stripeDensity: 40,
      displacement: 10,
      verticalSpeed: 0,
      rgbSplit: 15,
      rgbSplitDirection: 0,
      rgbSplitDirectionAnim: false,
      clipShape: 'none',
      duotone: false,
      duotoneLightColor: '#e7305e',
      duotoneDarkColor: '#2e3060',
      dotSize: 2.2,
      dotOpacity: 0.28,
    },
  },
  {
    id: 'cyber-pulse',
    name: 'Cyber Pulse',
    nameZh: '赛博脉冲',
    params: {
      stripeDensity: 20,
      displacement: 18,
      verticalSpeed: 0,
      rgbSplit: 25,
      rgbSplitDirection: 0,
      rgbSplitDirectionAnim: false,
      clipShape: 'none',
      duotone: false,
      duotoneLightColor: '#e7305e',
      duotoneDarkColor: '#2e3060',
      dotSize: 2.2,
      dotOpacity: 0.28,
    },
  },
]

export const DEFAULT_GLITCH_PARAMS: GlitchParams = {
  stripeDensity: 0,
  displacement: 0,
  verticalSpeed: 0,
  rgbSplit: 0,
  rgbSplitDirection: 0,
  rgbSplitDirectionAnim: false,
  clipShape: 'none',
  duotone: false,
  duotoneLightColor: '#e7305e',
  duotoneDarkColor: '#2e3060',
  dotSize: 2.2,
  dotOpacity: 0.28,
}
