import { GlitchParams, AsciiParams, EffectType } from '@/types'

export async function exportPNG(canvas: HTMLCanvasElement, filename: string): Promise<void> {
  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (!blob) return
      downloadBlob(blob, `${filename}.png`)
      resolve()
    }, 'image/png')
  })
}

export async function exportJPEG(canvas: HTMLCanvasElement, filename: string): Promise<void> {
  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (!blob) return
      downloadBlob(blob, `${filename}.jpg`)
      resolve()
    }, 'image/jpeg', 0.92)
  })
}

export async function exportSVG(canvas: HTMLCanvasElement, filename: string): Promise<void> {
  const dataURL = canvas.toDataURL('image/png')
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${canvas.width}" height="${canvas.height}">
  <image href="${dataURL}" width="${canvas.width}" height="${canvas.height}"/>
</svg>`
  const blob = new Blob([svg], { type: 'image/svg+xml' })
  downloadBlob(blob, `${filename}.svg`)
}

export async function exportPDF(canvas: HTMLCanvasElement, _filename: string): Promise<void> {
  const dataURL = canvas.toDataURL('image/png')
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`<!DOCTYPE html><html><head><title>Export PDF</title><style>@media print{@page{size:${canvas.width}px ${canvas.height}px;margin:0}body{margin:0}}body{margin:0;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#000}</style></head><body><img src="${dataURL}" style="max-width:100%;max-height:100vh" onload="setTimeout(()=>{window.print();window.close()},200)"/></body></html>`)
  win.document.close()
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export async function exportGIF(
  canvas: HTMLCanvasElement,
  renderFrame: (frameIndex: number) => void,
  options: { frames: number; delay: number; filename: string }
): Promise<void> {
  const { default: GIF } = await import('gif.js')

  const gif = new GIF({
    workers: 2,
    quality: 10,
    width: canvas.width,
    height: canvas.height,
    workerScript: '/gif.worker.js',
  })

  for (let i = 0; i < options.frames; i++) {
    renderFrame(i)
    gif.addFrame(canvas, { copy: true, delay: options.delay })
  }

  return new Promise((resolve) => {
    gif.on('finished', (blob: Blob) => {
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${options.filename}.gif`
      a.click()
      URL.revokeObjectURL(url)
      resolve()
    })
    gif.render()
  })
}

export function generateHTMLCode(
  effect: EffectType,
  params: GlitchParams | AsciiParams
): string {
  if (effect === 'glitch') {
    return generateGlitchHTML(params as GlitchParams)
  }
  return generateAsciiHTML(params as AsciiParams)
}

export function generateCanvasCode(
  effect: EffectType,
  params: GlitchParams | AsciiParams
): string {
  if (effect === 'glitch') {
    return generateGlitchCanvasCode(params as GlitchParams)
  }
  return generateAsciiCanvasCode(params as AsciiParams)
}

function generateGlitchHTML(params: GlitchParams): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Glitch Effect - Generated by Nano Design</title>
  <style>
    body { margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #000; }
    canvas { max-width: 100%; max-height: 100vh; }
  </style>
</head>
<body>
  <canvas id="glitchCanvas"></canvas>
  <script>
    // Glitch Effect - Generated by Nano Design
    // Parameters: ${JSON.stringify(params, null, 2)}

    const canvas = document.getElementById('glitchCanvas');
    const ctx = canvas.getContext('2d');
    const params = ${JSON.stringify(params)};

    // Replace with your image source
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      canvas.width = img.width;
      canvas.height = img.height;
      renderGlitch();
    };
    img.src = 'YOUR_IMAGE_URL_HERE';

    function seededRandom(seed) {
      return function() {
        seed |= 0;
        seed = (seed + 0x6d2b79f5) | 0;
        let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
      };
    }

    let frame = 0;
    function renderGlitch() {
      const seed = params.animation ? params.randomSeed + Math.floor(frame * params.animationSpeed * 0.1) : params.randomSeed;
      const random = seededRandom(seed);
      ctx.clearRect(0, 0, canvas.width, canvas.height);

      const stripeCount = Math.max(1, Math.floor(params.stripeDensity * 0.5));
      const stripeHeight = canvas.height / stripeCount;

      for (let i = 0; i < stripeCount; i++) {
        const offsetX = (random() - 0.5) * params.displacement * 2;
        ctx.drawImage(img, 0, (i * img.height) / stripeCount, img.width, img.height / stripeCount,
          offsetX, i * stripeHeight, canvas.width, stripeHeight + 1);
      }

      if (params.animation) {
        frame++;
        requestAnimationFrame(renderGlitch);
      }
    }
  </script>
</body>
</html>`
}

function generateAsciiHTML(params: AsciiParams): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ASCII Art - Generated by Nano Design</title>
  <style>
    body { margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: ${params.bgColor}; }
    canvas { max-width: 100%; max-height: 100vh; }
  </style>
</head>
<body>
  <canvas id="asciiCanvas"></canvas>
  <script>
    // ASCII Art Effect - Generated by Nano Design
    // Parameters: ${JSON.stringify(params, null, 2)}

    const canvas = document.getElementById('asciiCanvas');
    const ctx = canvas.getContext('2d');
    const params = ${JSON.stringify(params)};
    const charSets = { standard: ' .:-=+*#%@', minimal: ' .:+#', blocks: ' ░▒▓█' };
    const chars = params.charSet === 'custom' && params.customChars ? params.customChars : charSets[params.charSet] || charSets.standard;

    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      canvas.width = 800;
      canvas.height = 600;
      renderAscii();
    };
    img.src = 'YOUR_IMAGE_URL_HERE';

    function renderAscii() {
      const charWidth = params.fontSize * 0.6;
      const cols = Math.max(1, Math.floor((canvas.width * params.charDensity / 100) / charWidth));
      const rows = Math.max(1, Math.floor(cols * (img.height / img.width) * (charWidth / params.fontSize)));

      const sampleCanvas = document.createElement('canvas');
      sampleCanvas.width = cols; sampleCanvas.height = rows;
      const sCtx = sampleCanvas.getContext('2d');
      sCtx.drawImage(img, 0, 0, cols, rows);
      const pixels = sCtx.getImageData(0, 0, cols, rows).data;

      ctx.fillStyle = params.bgColor;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.font = params.fontSize + 'px monospace';
      ctx.textBaseline = 'top';

      const oX = (canvas.width - cols * charWidth) / 2;
      const oY = (canvas.height - rows * params.fontSize) / 2;

      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
          const i = (r * cols + c) * 4;
          let b = (0.299 * pixels[i] + 0.587 * pixels[i+1] + 0.114 * pixels[i+2]) / 255;
          if (params.invert) b = 1 - b;
          const ch = chars[Math.floor(b * (chars.length - 1))];
          ctx.fillStyle = params.colorMode === 'color' ? 'rgb('+pixels[i]+','+pixels[i+1]+','+pixels[i+2]+')' : params.colorMode === 'mono' ? (params.monoColor || '#0f0') : 'rgb('+Math.floor(b*255)+','+Math.floor(b*255)+','+Math.floor(b*255)+')';
          ctx.fillText(ch, oX + c * charWidth, oY + r * params.fontSize);
        }
      }
    }
  </script>
</body>
</html>`
}

function generateGlitchCanvasCode(params: GlitchParams): string {
  return `// Glitch Effect - Canvas Code
// Generated by Nano Design
// Parameters: ${JSON.stringify(params)}

function seededRandom(seed) {
  return function() {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function renderGlitch(ctx, img, params, frame) {
  const seed = params.animation ? params.randomSeed + Math.floor(frame * params.animationSpeed * 0.1) : params.randomSeed;
  const random = seededRandom(seed);
  const w = ctx.canvas.width, h = ctx.canvas.height;
  ctx.clearRect(0, 0, w, h);

  const stripeCount = Math.max(1, Math.floor(params.stripeDensity * 0.5));
  const stripeHeight = h / stripeCount;

  for (let i = 0; i < stripeCount; i++) {
    const offsetX = (random() - 0.5) * params.displacement * 2;
    ctx.drawImage(img, 0, (i * img.height) / stripeCount, img.width, img.height / stripeCount,
      offsetX, i * stripeHeight, w, stripeHeight + 1);
  }
}

// Usage:
// const canvas = document.getElementById('myCanvas');
// const ctx = canvas.getContext('2d');
// const img = new Image();
// img.onload = () => renderGlitch(ctx, img, ${JSON.stringify(params)}, 0);
// img.src = 'your-image.jpg';
`
}

function generateAsciiCanvasCode(params: AsciiParams): string {
  return `// ASCII Art - Canvas Code
// Generated by Nano Design
// Parameters: ${JSON.stringify(params)}

const charSets = { standard: ' .:-=+*#%@', minimal: ' .:+#', blocks: ' ░▒▓█' };

function renderAscii(ctx, img, params) {
  const chars = params.charSet === 'custom' && params.customChars ? params.customChars : charSets[params.charSet] || charSets.standard;
  const w = ctx.canvas.width, h = ctx.canvas.height;
  const charWidth = params.fontSize * 0.6;
  const cols = Math.max(1, Math.floor((w * params.charDensity / 100) / charWidth));
  const rows = Math.max(1, Math.floor(cols * (img.height / img.width) * (charWidth / params.fontSize)));

  const sc = document.createElement('canvas');
  sc.width = cols; sc.height = rows;
  sc.getContext('2d').drawImage(img, 0, 0, cols, rows);
  const px = sc.getContext('2d').getImageData(0, 0, cols, rows).data;

  ctx.fillStyle = params.bgColor;
  ctx.fillRect(0, 0, w, h);
  ctx.font = params.fontSize + 'px monospace';
  ctx.textBaseline = 'top';
  const oX = (w - cols * charWidth) / 2, oY = (h - rows * params.fontSize) / 2;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const i = (r * cols + c) * 4;
      let b = (0.299 * px[i] + 0.587 * px[i+1] + 0.114 * px[i+2]) / 255;
      if (params.invert) b = 1 - b;
      ctx.fillStyle = params.colorMode === 'color' ? 'rgb('+px[i]+','+px[i+1]+','+px[i+2]+')' : params.colorMode === 'mono' ? (params.monoColor || '#0f0') : 'rgb('+Math.floor(b*255)+','+Math.floor(b*255)+','+Math.floor(b*255)+')';
      ctx.fillText(chars[Math.floor(b * (chars.length - 1))], oX + c * charWidth, oY + r * params.fontSize);
    }
  }
}

// Usage:
// const canvas = document.getElementById('myCanvas');
// const ctx = canvas.getContext('2d');
// const img = new Image();
// img.onload = () => renderAscii(ctx, img, ${JSON.stringify(params)});
// img.src = 'your-image.jpg';
`
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}
